<?xml version="1.0" encoding="utf-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd">
	<!--Generated by GeoCat Bridge for QGIS 4.4 (based on bridgestyle 0.1)-->
	<NamedLayer>
		<Name>IDENA_DOTACI_Sym_PtosAgua</Name>
		<UserStyle>
			<Name>IDENA_DOTACI_Sym_PtosAgua</Name>
			<Title>IDENA_DOTACI_Sym_PtosAgua</Title>
			<FeatureTypeStyle>
				<!-- ============== Puntos clasificados por terrestre, aéreos y mixtos ============== -->
				<Rule>
					<Name>Balsas para medios terrestres</Name>
					<ogc:Filter>
						<ogc:Or>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>&lt; 250 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>1</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>250-750 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>1</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>750-5.000 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>1</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>1</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
						</ogc:Or>
					</ogc:Filter>
					<MinScaleDenominator>30000</MinScaleDenominator>
					<MaxScaleDenominator>3000000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
									<CssParameter name="fill">#c87137</CssParameter>
								</Fill>
								<Stroke>
									<CssParameter name="stroke">#FFFFFF</CssParameter>
									<CssParameter name="stroke-width">0.9</CssParameter>
								</Stroke>
							</Mark>
							<Size>8</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas para medios aéreos</Name>
					<ogc:Filter>
						<ogc:Or>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>&lt; 250 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>2</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>250-750 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>2</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>750-5.000 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>2</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>2</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
						</ogc:Or>
					</ogc:Filter>
					<MinScaleDenominator>30000</MinScaleDenominator>
					<MaxScaleDenominator>3000000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
									<CssParameter name="fill">#3f48cc</CssParameter>
								</Fill>
								<Stroke>
									<CssParameter name="stroke">#FFFFFF</CssParameter>
									<CssParameter name="stroke-width">0.9</CssParameter>
								</Stroke>
							</Mark>
							<Size>8</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas para medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:Or>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>&lt; 250 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>250-750 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>750-5.000 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
						</ogc:Or>
					</ogc:Filter>
					<MinScaleDenominator>30000</MinScaleDenominator>
					<MaxScaleDenominator>3000000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
									<CssParameter name="fill">#00aa00</CssParameter>
								</Fill>
								<Stroke>
									<CssParameter name="stroke">#FFFFFF</CssParameter>
									<CssParameter name="stroke-width">0.9</CssParameter>
								</Stroke>
							</Mark>
							<Size>8</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<!-- ============== FIN Puntos clasificados por terrestre, aéreos y mixtos ============== -->

				<Rule>
					<Name>&lt; 250 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>18</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>22</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>70</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>18</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>22</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>70</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>18</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>22</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&lt; 250 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&lt; 250 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>70</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>23</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>27</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>80</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>23</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>27</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>80</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>23</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>27</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>250-750 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>250-750 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>80</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>28</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>32</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>90</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>28</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>32</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>90</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>28</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>32</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>750-5.000 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>750-5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>90</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>32</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>38</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>100</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>32</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>38</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>100</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>32</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>38</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>&gt; 5.000 m3 medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>&gt; 5.000 m3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>100</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<!---->
				<!-- Desconocidos a escala 3000000 - 30000 -->
				<Rule>
					<Name>Capacidad desconocida</Name>
					<ogc:Filter>
						<ogc:Or>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>Desconocido</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>1</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>Desconocido</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>2</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
							<ogc:And>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
									<ogc:Literal>Desconocido</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>CTIPO</ogc:PropertyName>
									<ogc:Literal>3</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:And>
						</ogc:Or>
					</ogc:Filter>
					<MinScaleDenominator>30000</MinScaleDenominator>
					<MaxScaleDenominator>3000000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
									<CssParameter name="fill">#9B9B9b</CssParameter>
								</Fill>
								<Stroke>
									<CssParameter name="stroke">#FFFFFF</CssParameter>
									<CssParameter name="stroke-width">0.9</CssParameter>
								</Stroke>
							</Mark>
							<Size>8</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>25</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>29</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>1</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_tierra_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>85</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>25</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>29</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios aéreos</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>2</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_aereo_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>85</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>10000</MinScaleDenominator>
					<MaxScaleDenominator>30000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>25</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>1500</MinScaleDenominator>
					<MaxScaleDenominator>10000</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>29</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Balsas con capacidad desconocida para medios aéreos y terrestres</Name>
					<ogc:Filter>
						<ogc:And>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>IDCAPACIDA</ogc:PropertyName>
								<ogc:Literal>Desconocido</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>CTIPO</ogc:PropertyName>
								<ogc:Literal>3</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
					<MinScaleDenominator>0</MinScaleDenominator>
					<MaxScaleDenominator>1500</MaxScaleDenominator>
					<PointSymbolizer>
						<Graphic>
							<ExternalGraphic>
								<OnlineResource xlink:type="simple" xlink:href="DOTACI_Sym_PtosAgua_mixto_desconocido.svg"/>
								<Format>image/svg+xml</Format>
							</ExternalGraphic>
							<Size>85</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
			</FeatureTypeStyle>
		</UserStyle>
	</NamedLayer>
</StyledLayerDescriptor>